name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-manifests:
    name: Test Kubernetes Manifests
    runs-on: ubuntu-latest
    container:
      image: shopsys/kubernetes-buildpack:2.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run manifest tests
        run: ./tests/run-tests.sh
